
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Remove existing node_modules
        run: rm -rf node_modules

      - name: Install dependencies (check cache)
        run: yarn install --check-cache

      - name: Build Strapi project
        run: yarn build

      - name: Prepare SSH Key
        run: |
          echo "${KEY}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -i key.pem $EC2_USER@$EC2_HOST "mkdir -p ~/strapi"
          scp -i key.pem -r ./* $EC2_USER@$EC2_HOST:~/strapi
          ssh -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/strapi
            yarn install --check-cache
            yarn build
            pm2 restart strapi
          EOF
